# Generated by Django 6.0.4 on 2026-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('attempt_type', models.CharField(choices=[('failed', 'Failed Login Attempt'), ('success', 'Successful Login')], default='failed', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent header for tracking device/browser')),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', '-timestamp'], name='manzi_login_usernam_30ed67_idx'), models.Index(fields=['ip_address', '-timestamp'], name='manzi_login_ip_addr_7f9c33_idx'), models.Index(fields=['attempt_type', '-timestamp'], name='manzi_login_attempt_9f443d_idx')],
            },
        ),
    ]
