# Generated by Django 6.0.4 on 2026-04-15 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manzi', '0002_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth_registration', 'User Registration'), ('auth_login_success', 'Successful Login'), ('auth_login_failure', 'Failed Login'), ('auth_logout', 'Logout'), ('auth_password_change', 'Password Change'), ('auth_password_reset_request', 'Password Reset Request'), ('auth_password_reset_confirm', 'Password Reset Confirmed'), ('auth_permission_change', 'Permission/Role Change'), ('security_suspicious_activity', 'Suspicious Activity')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_logs', 'Can view audit logs'), ('export_audit_logs', 'Can export audit logs')],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='manzi_audit_event_t_aabbbc_idx'), models.Index(fields=['username', '-timestamp'], name='manzi_audit_usernam_578f3e_idx'), models.Index(fields=['user', '-timestamp'], name='manzi_audit_user_id_ed65a5_idx'), models.Index(fields=['severity', '-timestamp'], name='manzi_audit_severit_5613bb_idx')],
            },
        ),
    ]
